Update index.md
PrismLibrary/Prism-Documentation pull request #109
Opened 2021-04-18 15:48 UTC by leocdi

Removed 'and [Register Pages for Navigation](../navigation/navigation-basics.md)' because this page does not exists anymore.

2021-04-18 15:48 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/PrismLibrary/Prism-Documentation?pullRequest=109) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/PrismLibrary/Prism-Documentation?pullRequest=109) before we can accept your contribution.<br/><br/>:x: leocdi [sign now](https://cla.dotnetfoundation.org/PrismLibrary/Prism-Documentation?pullRequest=109)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/PrismLibrary/Prism-Documentation?pullRequest=109) it.</sub>

2021-04-18 22:14 UTC, dansiegel requested changes

2021-04-18 22:14 UTC, dansiegel commented on docs/dependency-injection/index.md
> -- Learn how to [Register Services](registering-types.md) and [Register Pages for Navigation](../navigation/navigation-basics.md)
it would appear that the correct link would be: ../xamarin-forms/navigation/navigation-basics.md

2021-04-19 20:38 UTC, dansiegel approved these changes

2021-04-19 20:38 UTC, merged

2021-04-19 20:38 UTC, dansiegel commented
thanks for the PR