Partial views
PrismLibrary/Prism-Documentation pull request #52
Opened 2019-11-25 16:54 UTC by ScarlettCode

Closes #45 

I've added what I think is necessary to get someone going with this. Took details from the change log and a stack overflow answer. 

Under what section should this be added under the docs navigation menu?
I didn't see a topic under the sample repo for this? If we add one I can create a sample to match the docs. 

Let me know if there is anything else I need to add or tweak for this

2019-11-26 15:41 UTC, dansiegel requested changes

2019-11-26 15:41 UTC, dansiegel commented on docs/xamarin-forms/partial-views.md
> +```csharp
this would be xml not csharp

2019-11-26 15:41 UTC, dansiegel commented on docs/xamarin-forms/partial-views.md
> +```csharp
this is also xml not csharp

2020-01-15 21:47 UTC, ScarlettCode commented
I think this is no longer relevant come Prism 8 and regions?

2020-01-15 21:49 UTC, dansiegel commented
Thanks for the PR.. we're going to close this one out as Partial Views will be discontinued and replaced by Regions in Prism 8.

2020-01-15 21:49 UTC, closed without merging